server:
  port: 8090

logging:
  level:
    root: INFO
    '[org.springframework.http]': TRACE
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': TRACE
    '[org.springframework.security.oauth2]': TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
